replicaCount: 1

image:
  repository: 073702999080.dkr.ecr.us-east-1.amazonaws.com/artemis:2.0.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0.0"

imagePullSecrets: 
  - regcred